name: Build Qt Project with MinGW

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    # 安装 Ninja
    - name: Install Ninja
      run: choco install ninja

    # 安装 MinGW
    - name: Install MinGW
      run: choco install mingw

    # 设置 MinGW 环境变量
    - name: Add MinGW to PATH
      shell: powershell
      run: echo "C:\\tools\\mingw64\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    # 安装 Qt（使用 Qt 6.5.2 是因为 6.9.1 MinGW 缺模块风险更大）
    - name: Install Qt (MinGW full)
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.2'
        target: desktop
        arch: win64_mingw
        # 不加 modules，安装完整包（包含 qttools）

    # 编译项目
    - name: Configure CMake
      run: cmake -S . -B build -G Ninja -DCMAKE_PREFIX_PATH=${{ github.workspace }}/Qt/6.5.2/mingw_64/lib/cmake

    - name: Build with Ninja
      run: cmake --build build --parallel

    # 打包依赖 DLL（可选：windeployqt）
    - name: Run windeployqt
      shell: pwsh
      run: |
        & "D:/a/test/test/Qt/6.5.2/mingw_64/bin/windeployqt.exe" build/learn.exe


    # 上传构建产物
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: learn-qt-mingw
        path: build/
