name: Build Qt Project with MinGW

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 拉取项目源码
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 安装 Ninja 构建工具
    - name: Install Ninja
      run: choco install ninja

    # 安装 MinGW
    - name: Install MinGW
      run: choco install mingw

    # 把 MinGW 路径加入 PATH
    - name: Add MinGW to PATH
      shell: powershell
      run: echo "C:\\tools\\mingw64\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    # 安装 Qt（MinGW 版本，完整包）
    - name: Install Qt 6.5.2
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.2'
        target: desktop
        arch: win64_mingw
        cache: true

    # 用 CMake 配置（指定 Qt 安装路径）
    - name: Configure CMake
      run: |
        cmake -S . -B build -G Ninja -DCMAKE_PREFIX_PATH="${{ env.Qt6_DIR }}"

    # 构建项目
    - name: Build Project
      run: cmake --build build --parallel


    # 上传构建产物（可选）
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: V1-build
        path: build/
